# This file relates to internal XMOS infrastructure and should be ignored by external users

lib_name: lib_adat
project: '{{lib_name}}'
title: '{{lib_name}}: ADAT lightpipe'
version: 2.0.1

documentation:
  exclude_patterns_path: doc/exclude_patterns.inc
  root_doc: doc/rst/lib_adat.rst
  cognidox_part_number: XM-015136-UG
  doxygen_projects:
    lib_adat:
      doxyfile_path: doc/Doxyfile.inc
  pdfs:
    doc/rst/lib_adat.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{lib_name}}_v{{version}}'
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{lib_name}}_v{{version}}_readme'
      pdf_short: yes
software:
  cognidox_part_number: XM-XM-015137-SM
